Add toc
boxfish-studio/liebling pull request #2
Opened 2021-09-16 14:14 UTC by evavirseda

Update scss with tocbot

2022-04-01 16:12 UTC, rubalv96 requested changes
Pequeñas cosillas 🚀 💪🏼

2022-04-01 16:12 UTC, rubalv96 commented on src/sass/common/_global.scss
> +    background-color: white;
Creo que es mejor no poner un background white (ni de otro color) es mejor que se adapta al color de fondo de la pagina así en caso de dark mode podemos verlo mejor.
![image](https://user-images.githubusercontent.com/36295331/161295765-86c633f0-93ff-4d3e-956f-a0ba8bd8b5fc.png)

2022-04-01 16:12 UTC, rubalv96 commented on src/sass/common/_global.scss
> +    padding-bottom: 10px;
este padding produce un hueco feo blanco, creo que no necesitamos ese padding.
![image](https://user-images.githubusercontent.com/36295331/161299962-2ca61c82-6771-4e55-ac72-00bb52ac6ddb.png)

2022-04-01 16:12 UTC, rubalv96 commented on src/sass/common/_global.scss
> +    margin-left: -20px;
creo que no lo necesitamos

2022-04-01 16:12 UTC, rubalv96 commented on src/sass/common/_global.scss
> +            top: 0;
si quitamos el margin de arriba, podemos sufragar el problema de que la navbar tape el ToC con un top aquí que sea igual o superior a la altura del navbar

2022-04-01 16:12 UTC, rubalv96 commented on src/sass/common/_global.scss
> +            width: 40%;
Creo que es mejor utilizar numeros concretos de pixeles. Y en lugar de usar un left mejor usar un right.
Por ejemplo,

width: 250px;
right: -250px - 64px =>>> right: -314px

así tenemos más controlada la posición

2022-04-01 16:12 UTC, rubalv96 commented on src/sass/common/_global.scss
> +            background-color: white;
mejor no meter el white para no tener problemas con dark mode

2022-04-04 09:30 UTC, rubalv96 requested changes
Mucho mejor así, mini detaillitos:
¿habría alguna forma de ocultar el ToC bajo esta sección?
![image](https://user-images.githubusercontent.com/36295331/161515834-42586f11-348e-4f9c-9863-cd6dcd2c85c8.png)

2022-04-04 09:30 UTC, rubalv96 commented on src/sass/common/_global.scss
> +    background-color: var(--background-color);
Yo creo que podemos dejarlo sin fondo (es decir un fondo transparente), por si acaso en algún momento se cambia el color de fondo, o solapa con respecto alguna imagen con un fondo diferente, así no se ve ese fondo. Por ejemplo aquí:
![image](https://user-images.githubusercontent.com/36295331/161514853-acd8e346-b30a-47a5-869e-de720558ce2e.png)

2022-04-04 09:56 UTC, evavirseda commented on src/sass/common/_global.scss
> +    background-color: var(--background-color);
si ponemos background transparent, en mobile no se vería bien, por eso he puesto el background con las variables del theme

2022-04-04 11:04 UTC, rubalv96 requested changes
💪🏼

2022-04-04 11:04 UTC, rubalv96 commented on src/sass/common/_global.scss
> +    z-index: 0;
https://www.awesomescreenshot.com/video/8220673?key=c79f14d2a468a9118434838f19c998d4 
 z-index 🙈

2022-04-04 11:04 UTC, rubalv96 commented on src/sass/common/_global.scss
>      margin-left: -20px;
¿Podemos meter un padding top para evitar que se solape la navbar?
Solo en mobile
https://www.awesomescreenshot.com/video/8220734?key=6b1545db60682bf82f3e2b86e4eacf09

2022-04-05 15:59 UTC, evavirseda commented on src/sass/common/_global.scss
> +    z-index: 0;
[Fixed](https://www.awesomescreenshot.com/video/8247914?key=b7f81bbb027b610cb3ccacc9767471fb)

2022-11-25 13:13 UTC, closed without merging