feat:  Add CI to build theme artifact (IOTA)
boxfish-studio/liebling pull request #24
Opened 2023-01-05 07:50 UTC by evavirseda

Closes #13

2023-01-17 15:19 UTC, begonaalvarezd requested changes

2023-01-17 15:19 UTC, begonaalvarezd commented on .github/workflows/deploy-theme.yaml
> +        uses: TryGhost/action-deploy-theme@v1.6.1
I think i prefer not using this action for now, this is to upload directly the theme to a server, but I think we are safer just creating the artifact and be able to download it from the gh action panel. in localhost I use `yarn production`, can we do something similar to what localhost does just to generate the zip?

2023-01-18 12:09 UTC, cpl121 approved these changes
Amazing 💯

2023-01-19 14:17 UTC, cpl121 reviewed
1 question

2023-01-19 14:17 UTC, cpl121 commented on .github/workflows/build-artifact-assembly.yaml
> +        run: cd src && cd .. && zip -r liebling.zip ./* -x 'node_modules/*' -x '*src*'
Is it necessary to go into the src folder and exit? `cd src && cd ..`

2023-01-19 14:17 UTC, cpl121 commented on .github/workflows/build-artifact-iota.yaml
> +        run: cd src && cd .. && zip -r liebling.zip ./* -x 'node_modules/*' -x '*src*'
same

2023-01-19 14:17 UTC, cpl121 commented on .github/workflows/build-artifact-shimmer.yaml
> +        run: cd src && cd .. && zip -r liebling.zip ./* -x 'node_modules/*' -x '*src*'
same

2023-01-19 14:25 UTC, evavirseda commented on .github/workflows/build-artifact-assembly.yaml
> +        run: cd src && cd .. && zip -r liebling.zip ./* -x 'node_modules/*' -x '*src*'
Oh, you're right. I used to have to go to `src` file when using `yarn production`. I'll change it! Thanks!

2023-01-19 16:08 UTC, cpl121 approved these changes
LGTM 💯

2023-01-23 12:34 UTC, merged